apiVersion: v1
kind: Service
metadata:
  name: fruit-store
spec:
  selector:
    app: fruit-store
  ports:
    - port: 80
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fruit-store
spec:
  selector:
    matchLabels:
      app: fruit-store
  template:
    metadata:
      labels:
        app: fruit-store
    spec:
      containers:
        - name: fruit-store
          image: quarkus/fruit-store:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "64Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
